---
development:
  cloud_name: harooncloudblog
  api_key: '391548427977735'
  api_secret: uyhBz3qn6L4zJVk6b9cZ1HYJnJI
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: harooncloudblog
  api_key: '391548427977735'
  api_secret: uyhBz3qn6L4zJVk6b9cZ1HYJnJI
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: harooncloudblog
  api_key: '391548427977735'
  api_secret: uyhBz3qn6L4zJVk6b9cZ1HYJnJI
  enhance_image_tag: true
  static_file_support: false
