default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: hackerman1234 #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-blog-dev

test:
  <<: *default
  database: rails-blog-test

production:
  <<: *default
  database: rails-blog-prod
  username: postgres
  password: hackerman1234